name: Build

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  release:
    types:
      - published

  workflow_dispatch: {}

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.build.outputs.file }}
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Build sdist
      id: build
      run: |
        pipx run build --sdist
        echo "file=$(basename dist/*.tar.gz)" >> "$GITHUB_OUTPUT"

    - uses: actions/upload-artifact@v7
      with:
        name: vsfpng-sdist
        path: dist/*.tar.gz

  build-wheel:
    needs:
      - build-sdist
    strategy:
      matrix:
        include:
        - arch: linux_x86_64
          runs-on: ubuntu-latest
        - arch: linux_aarch64
          runs-on: ubuntu-24.04-arm
        - arch: macosx_x86_64
          runs-on: macos-15-intel
        - arch: macosx_arm64
          runs-on: macos-15
        - arch: win_amd64
          runs-on: windows-latest
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/download-artifact@v8
      with:
        path: sdist
        merge-multiple: true

    - uses: pypa/cibuildwheel@v3.4.0
      env:
        CIBW_BUILD: cp312-*
        CIBW_SKIP: cp312-musllinux* *-win32
        CIBW_CONFIG_SETTINGS: setup-args="-Db_lto=true"
        CIBW_CONFIG_SETTINGS_WINDOWS: >-
          setup-args="-Db_lto=true"
          setup-args="-Dprefer_static=true"
          setup-args="-Dcpp_link_args=-static"
        CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=15
      with:
        package-dir: sdist/${{ needs.build-sdist.outputs.file }}
        output-dir: dist

    - name: Fix tag
      shell: bash
      run: |
        cd dist
        for whl in *.whl; do
          pipx run wheel tags --remove --python-tag py3 --abi-tag none $whl
        done

    - uses: actions/upload-artifact@v7
      with:
        name: vsfpng-${{ matrix.arch }}
        path: dist

  publish:
    if: github.event_name == 'release'

    runs-on: ubuntu-latest
    needs:
      - build-sdist
      - build-wheel

    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
    - uses: actions/download-artifact@v8
      with:
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
